// STATIC ARRAY

// WHEN AND WHERE TO USE THEM

// 1 STORING AND ACCESSING SEQUENTIAL DATA (e.g. a list of names, a list of numbers, a list of objects, etc.)
// 2 TEMPORARLY STORING OBJECTS
// 3 USED BY IO ROUTINES AS BUFFERS
// 4 LOOKUP TABLES AND INVERSE LOOKUP TABLES
// 5 TO RETURN MULTIPLE VALUES FROM A FUNCTION
// 6 USED IN DYNAMIC PROGRAMMING TO CACHE ANSERS TO SUBPROBLEMS

// COMPLEXITY

// 1 ACCESSING AN ELEMENT IN AN ARRAY IS CONSTANT TIME O(1)

// FOR DYNAMIC ARRAYS

// 2 INSERTING AN ELEMENT IN AN ARRAY IS LINEAR TIME O(n)
// 3 DELETING AN ELEMENT IN AN ARRAY IS LINEAR TIME O(n)
// 4 SEARCHING FOR AN ELEMENT IN AN ARRAY IS LINEAR TIME O(n)
// 5 APPENDING AN ELEMENT TO AN ARRAY IS CONSTANT TIME O(1)
