// UNION FIND

// IS A DATA STRUCTURE THAT KEEPS TRACK OF ELEMENTS WICH ARE SPLIT INTO ONE OR MORE DISJOINT SETS. IT SUPPORTS TWO OPERATIONS: FIND AND UNION. FIND RETURNS THE SET THAT CONTAINS A GIVEN ELEMENT, AND UNION COMBINES TWO SETS INTO A SINGLE SET.

// FIND: FINDS THE SET THAT CONTAINS A GIVEN ELEMENT. IT DOES THIS BY FOLLOWING THE PARENT LINKS UNTIL IT REACHES A ROOT ELEMENT, WHICH IS THE REPRESENTATIVE MEMBER OF ITS SET.

// UNION: COMBINES TWO SETS INTO A SINGLE SET. IT DOES THIS BY MERGING THEIR TREES. THE ROOT OF ONE TREE BECOMES THE PARENT OF THE ROOT OF THE OTHER TREE.

// THE UNION FIND DATA STRUCTURE IS USUALLY USED TO DETERMINE IF A GRAPH CONTAINS A CYCLE. IF IT DOES, THEN THE CYCLE CAN BE FOUND BY FINDING THE SETS THAT CONTAIN THE TWO VERTICES THAT FORM THE EDGE.

// THE UNION FIND DATA STRUCTURE IS ALSO USED TO SOLVE THE DYNAMIC CONNECTIVITY PROBLEM. THE DYNAMIC CONNECTIVITY PROBLEM IS THE FOLLOWING: GIVEN A SET OF N OBJECTS, DESIGN AN ALGORITHM TO DETERMINE IF TWO OBJECTS ARE CONNECTED. IF THEY ARE CONNECTED, FIND A PATH BETWEEN THEM. IF THEY ARE NOT CONNECTED, CONNECT THEM.

// THE UNION FIND DATA STRUCTURE IS ALSO USED TO SOLVE THE PERCOLATION PROBLEM. THE PERCOLATION PROBLEM IS THE FOLLOWING: GIVEN A SYSTEM OF N SITES, MODELLED AS N BY N GRID OF SITES, WHERE EACH SITE IS EITHER OPEN OR BLOCKED, DETERMINE IF THE SYSTEM PERCOLATES. A SYSTEM PERCOLATES IF THERE IS A FULL SITE IN THE BOTTOM ROW. A FULL SITE IS AN OPEN SITE THAT CAN BE CONNECTED TO AN OPEN SITE IN THE TOP ROW VIA A SEQUENCE OF ADJACENT OPEN SITES. WE SAY TWO SITES ARE ADJACENT IF THEY ARE BOTH OPEN AND SHARE A COMMON SIDE.

// THE UNION FIND DATA STRUCTURE IS ALSO USED TO SOLVE THE EQUILIBRIUM PROBLEM. THE EQUILIBRIUM PROBLEM IS THE FOLLOWING: GIVEN N SITES, MODELLED AS N BY N GRID OF SITES, WHERE EACH SITE IS EITHER OPEN OR BLOCKED, DETERMINE IF THE SYSTEM PERCOLATES. A SYSTEM PERCOLATES IF THERE IS A FULL SITE IN THE BOTTOM ROW. A FULL SITE IS AN OPEN SITE THAT CAN BE CONNECTED TO AN OPEN SITE IN THE TOP ROW VIA A SEQUENCE OF ADJACENT OPEN SITES. WE SAY TWO SITES ARE ADJACENT IF THEY ARE BOTH OPEN AND SHARE A COMMON SIDE.
